import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config({ path: '.env' });
await mongoose.connect(process.env.MONGODB_URI);
const { calculateOrderPricing } = await import('./src/modules/food/orders/services/order-pricing.service.js');
const { FoodItem } = await import('./src/modules/food/admin/models/food.model.js');
const { getFoodMarkupMultiplier, applyFoodMarkup } = await import('./src/modules/food/admin/services/foodMarkup.service.js');
const it = await FoodItem.findOne({ name: 'Chicken', restaurantId: '6ac72460835e7da33e7b274d' }).lean();
const m = await getFoodMarkupMultiplier();
const shown = applyFoodMarkup(it.price, m);
console.log('restaurant price', it.price, 'multiplier', m, 'menu price shown to user', shown);
const dto = { restaurantId: '6ac72460835e7da33e7b274d', items: [{ itemId: String(it._id), name: it.name, price: shown, quantity: 1 }], deliveryAddress: { location: { coordinates: [75.8577, 22.7196] } } };
const p = await calculateOrderPricing('6ac000000000000000000001', dto);
console.log('checkout subtotal', p.subtotal ?? p.pricing?.subtotal, 'total', p.total ?? p.pricing?.total);
await mongoose.disconnect();
